name: Continuous Integration
env:
  EB_APPLICATION_NAME : "netcore-mymatch"
  EB_ENVIRONMENT_NAME : "Netcoremymatch-env"
  AWS_REGION_NAME : "eu-north-1"
  DEPLOY_PACKAGE_NAME: "netcore_app${{ github.sha }}.zip"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 📦
      uses: actions/checkout@v3
      
    - name: Setup .NET 🔧
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies 🗃
      run: dotnet restore
      
    - name: Build 🔨
      run: dotnet build --no-restore
      
    - name: Test 🔬
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish prod
      run: dotnet publish -r linux-x64 --configuration "Release" -o ../bundle;
      
    - name: Generate deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ../bundle -x '*.git*';
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
        version_label: ${{ github.sha }}
        region: ${{ env.AWS_REGION_NAME }}
        deployment_package: ${{ env.DEPLOY_PACKAGE_NAME }}
      
