name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 📦
      uses: actions/checkout@v3
      
    - name: Setup .NET 🔧
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies 🗃
      run: dotnet restore
      
    - name: Build 🔨
      run: dotnet build --no-restore
      
    - name: Test 🔬
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish prod
      run: dotnet publish -r linux-x64 --configuration "Release" --self-contained "true" -o ../site;
      
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: MyApplicationName
        environment_name: MyApplication-Environment
        version_label: ${{ github.run_id }}
        region: us-west-2
        deployment_package: deploy.zip
      
      
